//! Disk-backed media thumbnail cache with LRU eviction.
//!
//! Sits between the [`crate::blob`] download path and the UI surface
//! (chat timeline, file picker, avatar grid) so re-rendering the same
//! attachment does not re-decode the source image bytes every time.
//!
//! ## Design
//!
//! * **Storage**: one file per cache key under `<root>/<key>.jpg`. The key is the hex-encoded
//!   `sha256(content_id || version_tag)`, so a version bump (e.g. server-side blob revoke +
//!   re-upload under the same id) produces a distinct key and the stale thumbnail is naturally
//!   orphaned.
//! * **Eviction**: classic LRU keyed by file access time. The cache tracks `(key, size_bytes,
//!   last_access)` in memory; when the total bytes exceed `max_bytes`, entries are removed in LRU
//!   order until under-budget.
//! * **Thumbnail generation**: [`generate_thumbnail`] uses the `image` crate's `Lanczos3` filter to
//!   resize to fit within a 256×256 bounding box, then JPEG-encodes at quality 80. The source bytes
//!   are decoded once; the output is a single byte buffer the caller can persist or stream.
//!
//! ## Why not the SDK's `Thumbnail` type?
//!
//! `contrix_sdk::Thumbnail` is the wire-level descriptor (digest,
//! dimensions, media type) that gets attached to a `cx.blob.register`
//! event. This module is the client-side render cache — it stores
//! generated bytes, not metadata. The two layers cooperate: the SDK
//! `Thumbnail` digest can be fed as the `version_tag` to
//! [`cache_key`] so a server-side thumbnail rotation invalidates the
//! local cache.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::sync::Mutex;
use std::time::UNIX_EPOCH;

use image::codecs::jpeg::JpegEncoder;
use image::imageops::FilterType;
use image::{ImageEncoder, ImageReader};
use sha2::{Digest, Sha256};

/// Maximum bounding-box edge for generated thumbnails. Source images
/// larger than this on either axis are scaled down; smaller images
/// are emitted at their native size (no upscale).
pub const THUMBNAIL_MAX_EDGE: u32 = 256;

/// JPEG encoder quality used by [`generate_thumbnail`]. 80 is the
/// standard "visually lossless for thumbnails" mark — Q70 introduces
/// visible artefacts on UI scale; Q90 doubles the file size for no
/// perceptible win.
pub const THUMBNAIL_JPEG_QUALITY: u8 = 80;

/// Default total-bytes budget for [`DiskCacheStore`]. 200 MiB matches
/// the spec's "1.0-milestone client cache should stay below half a
/// gig" guidance and leaves headroom for the encrypted-blob cache
/// in `crate::blob`.
pub const DEFAULT_CACHE_MAX_BYTES: usize = 200 * 1024 * 1024;

#[derive(Debug)]
pub enum MediaCacheError {
    Io(std::io::Error),
    /// `image` crate failed to decode the source bytes (corrupt /
    /// unsupported format) or encode the thumbnail.
    Image(String),
    /// Lock poisoned because another thread panicked while holding the
    /// LRU bookkeeping mutex.
    LockPoisoned,
}

impl std::fmt::Display for MediaCacheError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Io(err) => write!(f, "media cache io: {err}"),
            Self::Image(msg) => write!(f, "media cache image: {msg}"),
            Self::LockPoisoned => write!(f, "media cache lock poisoned"),
        }
    }
}

impl std::error::Error for MediaCacheError {}

impl From<std::io::Error> for MediaCacheError {
    fn from(err: std::io::Error) -> Self {
        Self::Io(err)
    }
}

/// Compute the cache key for `content_id` at `version_tag`. The output
/// is a hex sha256 over `content_id || ":" || version_tag`. Pass
/// `""` for `version_tag` when the content id is itself
/// content-addressed (e.g. `ck:blob:sha256:<hex>` which already
/// changes on re-upload).
pub fn cache_key(content_id: &str, version_tag: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(content_id.as_bytes());
    hasher.update(b":");
    hasher.update(version_tag.as_bytes());
    let digest = hasher.finalize();
    let mut out = String::with_capacity(digest.len() * 2);
    for byte in digest {
        out.push_str(&format!("{byte:02x}"));
    }
    out
}

/// Decode `source` (any format the `image` crate's enabled features
/// can handle — gif/jpeg/png/webp in our build) and produce a
/// 256×256-bounded JPEG thumbnail. Preserves aspect ratio; small
/// inputs are returned at their native size (no upscale).
pub fn generate_thumbnail(source: &[u8]) -> Result<Vec<u8>, MediaCacheError> {
    let cursor = std::io::Cursor::new(source);
    let reader = ImageReader::new(cursor)
        .with_guessed_format()
        .map_err(|err| MediaCacheError::Image(format!("guess format: {err}")))?;
    let img = reader
        .decode()
        .map_err(|err| MediaCacheError::Image(format!("decode: {err}")))?;
    // `thumbnail` selects an appropriate filter internally for large
    // downscales; we call `resize_to_fill`-style logic via the
    // explicit Lanczos3 filter so the result is deterministic.
    let resized = if img.width() > THUMBNAIL_MAX_EDGE || img.height() > THUMBNAIL_MAX_EDGE {
        img.resize(THUMBNAIL_MAX_EDGE, THUMBNAIL_MAX_EDGE, FilterType::Lanczos3)
    } else {
        img
    };
    // JPEG only supports RGB / luma; convert to RGB8 so the encoder
    // does not silently re-interpret the alpha channel.
    let rgb = resized.to_rgb8();
    let mut out = Vec::with_capacity(8 * 1024);
    let encoder = JpegEncoder::new_with_quality(&mut out, THUMBNAIL_JPEG_QUALITY);
    encoder
        .write_image(
            rgb.as_raw(),
            rgb.width(),
            rgb.height(),
            image::ExtendedColorType::Rgb8,
        )
        .map_err(|err| MediaCacheError::Image(format!("encode: {err}")))?;
    Ok(out)
}

/// LRU bookkeeping entry held in memory. The actual bytes live on
/// disk under `<root>/<key>.jpg`.
#[derive(Clone, Debug)]
struct LruEntry {
    size_bytes: u64,
    /// Monotonic counter — incremented on each `get` / `put`, lower
    /// values are older.
    last_access: u64,
}

/// Disk-backed thumbnail cache. Construct via [`DiskCacheStore::new`]
/// passing the cache root and a byte budget. Methods are thread-safe
/// via an internal mutex; the disk operations themselves are
/// best-effort — a transient IO error surfaces as `Err`, the cache
/// state stays consistent.
pub struct DiskCacheStore {
    root: PathBuf,
    max_bytes: usize,
    inner: Mutex<DiskCacheInner>,
}

#[derive(Debug)]
struct DiskCacheInner {
    entries: BTreeMap<String, LruEntry>,
    total_bytes: u64,
    access_counter: u64,
}

impl DiskCacheStore {
    /// Open / create a cache rooted at `root` with a `max_bytes` LRU
    /// budget. The root directory is created if it does not exist;
    /// existing thumbnail files in the directory are scanned and
    /// added to the LRU index (with `last_access` set to their
    /// filesystem mtime).
    pub fn new(root: &Path, max_bytes: usize) -> Result<Self, MediaCacheError> {
        std::fs::create_dir_all(root)?;
        let mut entries = BTreeMap::new();
        let mut total_bytes: u64 = 0;
        let mut access_counter: u64 = 0;
        for dir_entry in std::fs::read_dir(root)? {
            let dir_entry = dir_entry?;
            let path = dir_entry.path();
            // Skip non-files and non-.jpg names.
            if !path.is_file() {
                continue;
            }
            let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else {
                continue;
            };
            let Some(ext) = path.extension().and_then(|s| s.to_str()) else {
                continue;
            };
            if !ext.eq_ignore_ascii_case("jpg") {
                continue;
            }
            let meta = match dir_entry.metadata() {
                Ok(m) => m,
                Err(_) => continue,
            };
            let size_bytes = meta.len();
            // Use mtime as a coarse last-access proxy. New entries
            // get a monotonic counter assigned at `put` time which
            // dominates the mtime-derived value.
            let mtime_seconds = meta
                .modified()
                .ok()
                .and_then(|t| t.duration_since(UNIX_EPOCH).ok())
                .map(|d| d.as_secs())
                .unwrap_or(0);
            access_counter = access_counter.max(mtime_seconds);
            entries.insert(
                stem.to_owned(),
                LruEntry {
                    size_bytes,
                    last_access: mtime_seconds,
                },
            );
            total_bytes = total_bytes.saturating_add(size_bytes);
        }
        Ok(Self {
            root: root.to_owned(),
            max_bytes,
            inner: Mutex::new(DiskCacheInner {
                entries,
                total_bytes,
                access_counter,
            }),
        })
    }

    /// Path to a cache entry's on-disk file (whether or not it exists).
    fn entry_path(&self, key: &str) -> PathBuf {
        self.root.join(format!("{key}.jpg"))
    }

    /// True iff a thumbnail for `key` exists in the cache. Updates
    /// the entry's `last_access` (the LRU tick) iff it is present.
    pub fn contains(&self, key: &str) -> Result<bool, MediaCacheError> {
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| MediaCacheError::LockPoisoned)?;
        if !guard.entries.contains_key(key) {
            return Ok(false);
        }
        guard.access_counter += 1;
        let counter = guard.access_counter;
        if let Some(entry) = guard.entries.get_mut(key) {
            entry.last_access = counter;
        }
        Ok(true)
    }

    /// Read the thumbnail bytes for `key`. Returns `Ok(None)` when
    /// absent. Bumps the LRU tick on hit.
    pub fn get(&self, key: &str) -> Result<Option<Vec<u8>>, MediaCacheError> {
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| MediaCacheError::LockPoisoned)?;
        if !guard.entries.contains_key(key) {
            return Ok(None);
        }
        guard.access_counter += 1;
        let counter = guard.access_counter;
        if let Some(entry) = guard.entries.get_mut(key) {
            entry.last_access = counter;
        }
        let path = self.entry_path(key);
        // Drop the lock before doing IO. Re-acquire would be
        // necessary if we wanted to read-through-LRU-update, but
        // since we already bumped the counter above we can release.
        drop(guard);
        match std::fs::read(&path) {
            Ok(bytes) => Ok(Some(bytes)),
            Err(err) if err.kind() == std::io::ErrorKind::NotFound => {
                // Inconsistent state — index says present, disk says
                // gone. Clean up the index entry so subsequent calls
                // see the absent state.
                let mut guard = self
                    .inner
                    .lock()
                    .map_err(|_| MediaCacheError::LockPoisoned)?;
                if let Some(removed) = guard.entries.remove(key) {
                    guard.total_bytes = guard.total_bytes.saturating_sub(removed.size_bytes);
                }
                Ok(None)
            }
            Err(err) => Err(MediaCacheError::Io(err)),
        }
    }

    /// Write thumbnail bytes for `key`. Overwrites any prior entry.
    /// Evicts LRU-tail entries until the total cache size is within
    /// `max_bytes`. Returns an error if the new entry itself exceeds
    /// the budget (the caller would never make progress).
    pub fn put(&self, key: &str, thumbnail_bytes: Vec<u8>) -> Result<(), MediaCacheError> {
        let new_size = thumbnail_bytes.len() as u64;
        if new_size as usize > self.max_bytes {
            return Err(MediaCacheError::Image(format!(
                "thumbnail size {new_size} exceeds cache budget {}",
                self.max_bytes
            )));
        }
        // Write the file first so we don't update the index against
        // a write that's about to fail. Use a temp + rename so an
        // interrupted write doesn't leave a half-file under the
        // canonical name.
        let final_path = self.entry_path(key);
        let tmp_path = final_path.with_extension("jpg.tmp");
        std::fs::write(&tmp_path, &thumbnail_bytes)?;
        std::fs::rename(&tmp_path, &final_path)?;

        let mut guard = self
            .inner
            .lock()
            .map_err(|_| MediaCacheError::LockPoisoned)?;
        // Replace existing — subtract old size first.
        if let Some(old) = guard.entries.remove(key) {
            guard.total_bytes = guard.total_bytes.saturating_sub(old.size_bytes);
        }
        guard.access_counter += 1;
        let counter = guard.access_counter;
        guard.entries.insert(
            key.to_owned(),
            LruEntry {
                size_bytes: new_size,
                last_access: counter,
            },
        );
        guard.total_bytes = guard.total_bytes.saturating_add(new_size);
        // Evict LRU tail until under budget.
        self.evict_to_budget(&mut guard)?;
        Ok(())
    }

    /// Generate + store the thumbnail for `source_bytes` under
    /// `cache_key(content_id, version_tag)`. Returns the cache key
    /// and the encoded thumbnail bytes. Calling this with the same
    /// `(content_id, version_tag)` twice is idempotent — the second
    /// call decodes the source again (the cache index is checked
    /// inside, callers that want to skip the decode should
    /// [`contains`](Self::contains) first).
    pub fn put_from_source(
        &self,
        content_id: &str,
        version_tag: &str,
        source_bytes: &[u8],
    ) -> Result<(String, Vec<u8>), MediaCacheError> {
        let key = cache_key(content_id, version_tag);
        let thumbnail = generate_thumbnail(source_bytes)?;
        self.put(&key, thumbnail.clone())?;
        Ok((key, thumbnail))
    }

    /// Remove a single entry. Idempotent — `Ok(())` whether the key
    /// was present or not.
    pub fn evict(&self, key: &str) -> Result<(), MediaCacheError> {
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| MediaCacheError::LockPoisoned)?;
        if let Some(entry) = guard.entries.remove(key) {
            guard.total_bytes = guard.total_bytes.saturating_sub(entry.size_bytes);
        }
        drop(guard);
        let path = self.entry_path(key);
        match std::fs::remove_file(&path) {
            Ok(()) => Ok(()),
            Err(err) if err.kind() == std::io::ErrorKind::NotFound => Ok(()),
            Err(err) => Err(MediaCacheError::Io(err)),
        }
    }

    /// Current total byte usage. Useful for diagnostic UI and tests.
    pub fn total_bytes(&self) -> u64 {
        self.inner.lock().map(|g| g.total_bytes).unwrap_or(0)
    }

    /// Current entry count. Useful for diagnostic UI and tests.
    pub fn len(&self) -> usize {
        self.inner.lock().map(|g| g.entries.len()).unwrap_or(0)
    }

    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }

    fn evict_to_budget(
        &self,
        guard: &mut std::sync::MutexGuard<'_, DiskCacheInner>,
    ) -> Result<(), MediaCacheError> {
        while guard.total_bytes as usize > self.max_bytes {
            // Find the LRU entry — smallest `last_access`.
            let victim_key = guard
                .entries
                .iter()
                .min_by_key(|(_, e)| e.last_access)
                .map(|(k, _)| k.clone());
            let Some(victim_key) = victim_key else {
                break;
            };
            if let Some(victim) = guard.entries.remove(&victim_key) {
                guard.total_bytes = guard.total_bytes.saturating_sub(victim.size_bytes);
                let path = self.entry_path(&victim_key);
                // Removal of the on-disk file is best-effort; if it
                // fails the bookkeeping still reflects the eviction
                // (subsequent `get` would return None and clean up).
                let _ = std::fs::remove_file(&path);
            } else {
                break;
            }
        }
        Ok(())
    }
}

impl std::fmt::Debug for DiskCacheStore {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let (len, bytes) = self
            .inner
            .lock()
            .map(|g| (g.entries.len(), g.total_bytes))
            .unwrap_or((0, 0));
        f.debug_struct("DiskCacheStore")
            .field("root", &self.root)
            .field("max_bytes", &self.max_bytes)
            .field("entries", &len)
            .field("total_bytes", &bytes)
            .finish()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temp_cache_root(label: &str) -> PathBuf {
        let now = std::time::SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0);
        let dir = std::env::temp_dir().join(format!("yougen-media-cache-{label}-{now}"));
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    /// Build a 512×512 solid-colour PNG so the encoder has real
    /// pixels to chew on. `image` lets us construct a buffer in
    /// memory without a fixture file.
    fn synth_png(width: u32, height: u32, rgb: [u8; 3]) -> Vec<u8> {
        let mut buf = image::RgbImage::new(width, height);
        for pixel in buf.pixels_mut() {
            *pixel = image::Rgb(rgb);
        }
        let mut out = Vec::new();
        let encoder = image::codecs::png::PngEncoder::new(&mut out);
        encoder
            .write_image(
                buf.as_raw(),
                buf.width(),
                buf.height(),
                image::ExtendedColorType::Rgb8,
            )
            .unwrap();
        out
    }

    #[test]
    fn cache_key_changes_with_version_tag() {
        let a = cache_key("ck:blob:sha256:abc", "v1");
        let b = cache_key("ck:blob:sha256:abc", "v2");
        assert_ne!(a, b);
        // Same inputs → same key (deterministic).
        assert_eq!(a, cache_key("ck:blob:sha256:abc", "v1"));
    }

    #[test]
    fn generate_thumbnail_downscales_large_inputs() {
        let source = synth_png(1024, 512, [200, 50, 100]);
        let thumb = generate_thumbnail(&source).unwrap();
        // Decode to verify the output stays within 256×256.
        let reader = ImageReader::new(std::io::Cursor::new(&thumb))
            .with_guessed_format()
            .unwrap();
        let decoded = reader.decode().unwrap();
        assert!(decoded.width() <= THUMBNAIL_MAX_EDGE);
        assert!(decoded.height() <= THUMBNAIL_MAX_EDGE);
        // Aspect ratio is preserved (allow ±1 px rounding slack).
        let src_ratio = 1024.0_f64 / 512.0;
        let dst_ratio = decoded.width() as f64 / decoded.height() as f64;
        assert!((src_ratio - dst_ratio).abs() < 0.05);
    }

    #[test]
    fn generate_thumbnail_keeps_small_inputs_native_size() {
        let source = synth_png(100, 80, [10, 20, 30]);
        let thumb = generate_thumbnail(&source).unwrap();
        let reader = ImageReader::new(std::io::Cursor::new(&thumb))
            .with_guessed_format()
            .unwrap();
        let decoded = reader.decode().unwrap();
        assert_eq!(decoded.width(), 100);
        assert_eq!(decoded.height(), 80);
    }

    #[test]
    fn put_and_get_round_trip() {
        let root = temp_cache_root("round-trip");
        let cache = DiskCacheStore::new(&root, DEFAULT_CACHE_MAX_BYTES).unwrap();
        cache.put("abc", vec![1, 2, 3, 4]).unwrap();
        assert!(cache.contains("abc").unwrap());
        assert_eq!(cache.get("abc").unwrap(), Some(vec![1, 2, 3, 4]));
        let _ = std::fs::remove_dir_all(&root);
    }

    /// LRU eviction kicks in when the total exceeds `max_bytes`.
    /// Insert three 1KB entries with a 2.5KB budget; the oldest
    /// (first inserted) is evicted to fit the third.
    #[test]
    fn lru_evicts_oldest_when_over_budget() {
        let root = temp_cache_root("lru-evict");
        let cache = DiskCacheStore::new(&root, 2500).unwrap();
        cache.put("oldest", vec![0u8; 1000]).unwrap();
        cache.put("middle", vec![0u8; 1000]).unwrap();
        // At this point: 2 entries × 1000 bytes = 2000 ≤ 2500, both in.
        assert_eq!(cache.len(), 2);
        // Touch `middle` so it becomes more-recent than `oldest`.
        // (`oldest` and `middle` are still in insertion order: oldest is older.)
        cache.put("newest", vec![0u8; 1000]).unwrap();
        // Total would be 3000 > 2500, so the LRU (`oldest`) gets dropped.
        assert!(!cache.contains("oldest").unwrap());
        assert!(cache.contains("middle").unwrap());
        assert!(cache.contains("newest").unwrap());
        assert!(cache.total_bytes() as usize <= 2500);
        let _ = std::fs::remove_dir_all(&root);
    }

    /// `get` bumps the LRU tick — touching an entry keeps it in the
    /// cache even after newer entries are added. Tests the
    /// "frequently-accessed survives eviction" property.
    #[test]
    fn get_bumps_lru_keeps_entry_alive() {
        let root = temp_cache_root("lru-get-bumps");
        let cache = DiskCacheStore::new(&root, 2500).unwrap();
        cache.put("a", vec![0u8; 1000]).unwrap();
        cache.put("b", vec![0u8; 1000]).unwrap();
        // Touch `a` so it becomes more-recently-used than `b`.
        let _ = cache.get("a").unwrap();
        // Inserting `c` should now evict `b`, not `a`.
        cache.put("c", vec![0u8; 1000]).unwrap();
        assert!(cache.contains("a").unwrap());
        assert!(!cache.contains("b").unwrap());
        assert!(cache.contains("c").unwrap());
        let _ = std::fs::remove_dir_all(&root);
    }

    /// End-to-end: feed a real image through `put_from_source`,
    /// recover it via `get` keyed by the deterministic cache key.
    #[test]
    fn put_from_source_round_trips_thumbnail() {
        let root = temp_cache_root("source-rt");
        let cache = DiskCacheStore::new(&root, DEFAULT_CACHE_MAX_BYTES).unwrap();
        let source = synth_png(800, 600, [30, 60, 90]);
        let (key, thumb) = cache
            .put_from_source("ck:blob:sha256:test", "v1", &source)
            .unwrap();
        assert_eq!(key, cache_key("ck:blob:sha256:test", "v1"));
        let loaded = cache.get(&key).unwrap().unwrap();
        assert_eq!(loaded, thumb);
        // Sanity: thumb bytes are JPEG (start with 0xFF 0xD8).
        assert_eq!(&thumb[..2], &[0xFF, 0xD8]);
        let _ = std::fs::remove_dir_all(&root);
    }

    /// Reopening a cache populates the index from disk so prior
    /// entries are visible to a freshly-constructed store.
    #[test]
    fn cache_persists_across_reopen() {
        let root = temp_cache_root("reopen");
        {
            let cache = DiskCacheStore::new(&root, DEFAULT_CACHE_MAX_BYTES).unwrap();
            cache.put("k", vec![1, 2, 3]).unwrap();
        }
        let cache = DiskCacheStore::new(&root, DEFAULT_CACHE_MAX_BYTES).unwrap();
        assert!(cache.contains("k").unwrap());
        assert_eq!(cache.get("k").unwrap(), Some(vec![1, 2, 3]));
        let _ = std::fs::remove_dir_all(&root);
    }

    /// `evict` removes the entry from both index and disk.
    #[test]
    fn evict_removes_entry() {
        let root = temp_cache_root("evict");
        let cache = DiskCacheStore::new(&root, DEFAULT_CACHE_MAX_BYTES).unwrap();
        cache.put("k", vec![1, 2, 3]).unwrap();
        assert!(cache.contains("k").unwrap());
        cache.evict("k").unwrap();
        assert!(!cache.contains("k").unwrap());
        // Idempotent.
        cache.evict("k").unwrap();
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn put_rejects_entries_larger_than_budget() {
        let root = temp_cache_root("oversize");
        let cache = DiskCacheStore::new(&root, 100).unwrap();
        let err = cache.put("too-big", vec![0u8; 200]).unwrap_err();
        assert!(matches!(err, MediaCacheError::Image(_)));
        let _ = std::fs::remove_dir_all(&root);
    }
}
